### ISSUE TITLE
[Suggestion] Text Colorization

### ISSUE THREAD

**Issue by McFarts** [netgfx/Phasetips#1]
Would this beyond the scope of this plugin since we can incorporate Phaser.Text? I'm sure there are plugins already for colorizing specific text through Phasers` method, right?

Just curious! :)

**Comment by netgfx** [comment]
I'm not familiar with a plugin that does that, however since you can add virtually any Phaser object inside the tooltip, you could create a group and add 2-3 Phaser.Text that are colored differently

**Comment by McFarts** [comment]
Aww okay sweet. Thanks so much for this plugin it's amazing!
