### ISSUE TITLE
tooltip not hidden using a mobile

### ISSUE THREAD

**Issue by kerphi** [netgfx/Phasetips#10]
When using Phasertips on a mobile application, the tooltips are shown when the finger touch the target but it never disappears.

Any idea to fix this problem ?

Example on my app (tooltips are the boxes with blue borders and white background): 

![image](https://cloud.githubusercontent.com/assets/328244/17649196/b48ddace-622e-11e6-9286-778ea8265540.png)

**Comment by netgfx** [comment]
Hm interesting... probably due to the events that register input. I will take a look.

**Comment by netgfx** [comment]
I have added a fix, please test to see if its working.

**Comment by kerphi** [comment]
Thank you. I'll check as soon as possible.

On Sun, Aug 14, 2016 at 8:45 PM, Michael Dobekidis <notifications@github.com

**Comment by kerphi** [comment]
So i justed tested your fix, and great news, it works !

The beavior is: i put my finger on the target and the tooltip show as long as i dont release my finger
