### ISSUE TITLE
License Inclusion Guideance Lacking

### ISSUE THREAD

**Issue by mentalisttraceur** [netgfx/Phasetips#16]
Hello,

Maybe I don't fully understand the MIT license due to lack of lawyer-ness, but I would appreciate clarification: Do you expect us to copaste the entire `LICENSE` file's contents into a comment in any other files from this project that are being served up from a web-server to an user's browser, or do you consider the couple lines mentioning copyright and a link to your site that are already in the files sufficient?

**Comment by netgfx** [comment]
I would recommend fully understanding the MIT license because 90% or more of software on GitHub or other open source systems uses it. In a little less lawyerly language
```
you CAN:
re-use the code freely for your own use,
re-use the code freely for non-commercial AND commercial re-distribution, whether in source or binary form.
you CANNOT:
claim authorship of the software,
thus you cannot attack the original author for using or publishing his original version.
So, yes, you CAN use MIT/X11-licensed plug-ins in your commercial application.

MIT/X11 is basically a simple contract that says:

Person or company X created Y.
Y belongs to X, but X is granting you the right to use it and do whatever you want with it.
X cannot be held accountable for anything that goes downhill with what you do with Y.
```
As found here: http://softwareengineering.stackexchange.com/questions/103273/can-i-use-mit-licence-plugins-in-my-commercial-web-site

**Comment by mentalisttraceur** [comment]
I think my question wasn't clear: I've been in the FLOSS world for years and am fairly well versed in the general gist of permissive and copyleft licenses. What I'm not clear about, precisely, is:

1. The exact legal requirements when sending a piece of MIT-licensed JavaScript to the _end user_'s browser from a web server.
2. Regardless of exact legal requirements, what your own preferences are on the matter.

So, put another way: if I include the `Phasetips.js` file on a website, do you want me to explicitly place the contents of, or a reference to, the `LICENSE` file somewhere on the web-server as well?

For example, should I generate a combined file from `LICENSE` and `Phasertips.js`? For example like so (using regular *nix shell commands):

    echo '/*' >Phasertips.with_license.js
    cat LICENSE >>Phasertips.with_license.js
    echo '*/' >>Phasertips.with_license.js
    cat Phasertips.js >>Phasertips.with_license.js

Or should I edit the header of `Phasertips.js` to just have link to the `LICENSE` file?

Or do you consider the existing header in `Phasertips.js` sufficient to refer to people to the rest of the information (since it mentions you and links to your website)?

And should I take care that JS minification preserve this header comment, with or without such a license including/referencing edit?

**Comment by netgfx** [comment]
I have no preference on the matter. So I would suggest
* have a copy of the `Licence` file to the web server
* No need to change `Phasetips.js` to include the `Licence` file

**Comment by mentalisttraceur** [comment]
Great, thanks for letting me know.
