### ISSUE TITLE
Add Cursor Option

### ISSUE THREAD

**Issue by McFarts** [netgfx/Phasetips#3]
Cursor for on hover and on out? Yay or nay? :)

(For example, pointer on hover, default on out)

`game.canvas.style.cursor = 'pointer';` works afaik

**Comment by netgfx** [comment]
Sure thing I can I add it.

**Comment by netgfx** [comment]
Added property enableCursor https://github.com/netgfx/Phasetips/commit/78769ba6e818d8f30dc533d04a48032913fec00b
