### ISSUE TITLE
Height of tip is off from the content

### ISSUE THREAD

**Issue by McFarts** [netgfx/Phasetips#4]
For example:
![](https://i.gyazo.com/e88f69b3f83ef2f48376d4b1970ee138.png)

See the extra padding below the text? It doesn't matter what you change the padding to, there seems to be that extra padding. Not sure if this is a Phaser.Text issue or how `tooltipContent` get's it height within the plugin?

**Comment by netgfx** [comment]
Are you using string or a Phaser.Text?

**Comment by McFarts** [comment]
@netgfx  I'm just using a string, but it looks like it converts it into Phaser.Text

```
 if (type === "string") {
            tooltipContent = new Phaser.Text(game, _padding / 2 + 2, _padding / 2 + 2, _content, _textStyle);
            tooltipContent.updateText();
            tooltipContent.update();
        }
```

Not sure.

**Comment by netgfx** [comment]
Just uploaded a fix that should make it possible to change the padding value now, try it out

**Comment by McFarts** [comment]
@netgfx  Hmm. Just tried the latest with the same padding and it's still the same.

I found a weird fix though. If I do:
`tooltipContent = new Phaser.Text(game, _padding / 2 + 2, _padding / 2 + 2, _content, _textStyle);`

I add 2 to the x and y values it seems like it centers the text just right in the middle. I'm using `font: 'bold 12px Tahoma',` if that makes a difference

**Comment by netgfx** [comment]
![phasetooltips](https://cloud.githubusercontent.com/assets/864248/10563192/9550a1a8-7587-11e5-9018-33e58079611d.png)

As you see there is a padding added by the Phaser.Text, if this can be solved by changing the user set padding then I would say this is resolved.

**Comment by McFarts** [comment]
Hmmm. Yeah, it just seems like the padding at the bottom seems a lot more ![](https://i.gyazo.com/45c011f040da90cc7cf98e303d68e29e.png) as compared to the top. It might just be the Tahoma font I'm using or something.

In any event, I just changed the x, y and add 2 to them to offset it a bit and yeah it's resolved I guess hehe :D
