### ISSUE TITLE
ReferenceError: game is not defined

### ISSUE THREAD

**Issue by nvurgaft** [netgfx/Phasetips#5]
1. Nice plugin, it's great
2. I'm using phasetips for a game that's loaded onto an Angular app, (correct me if I'm wrong) but phasetips.js is looking for the global game object, and in my case it couldn't find it so it aborted the game launch and the console gave me 
   `ReferenceError: game is not defined` on line 105: 
   `_this.mainGroup = game.add.group();`

I've circumvented this by explicitly providing the constructor with a game object. shouldn't something like this already be implemented? lets say if we're having more then one game on screen

**Comment by netgfx** [comment]
Yes you are right, it makes sense I will make the changes. 

Thanks.
