### ISSUE TITLE
[Suggestion] Highlight

### ISSUE THREAD

**Issue by McFarts** [netgfx/Phasetips#6]
I was thinking, in games like Path of Exile if you hover over your stash tab there is a small white faded border around it.

Same for Diablo, Diablo 2 and D3. Was thinking if that would be possible here upon hovering the object? Just trying to find ways to increase this awesome plugins` features.

It would be hard to read the outer edge of the pixels though if they are not white on black or whatnot? Not sure how to do it

**Comment by netgfx** [comment]
Nice suggestion, can you provide a screenshot if that effect, and I can give it a try.

**Comment by McFarts** [comment]
Sweet, I logged in and got it:

!(https://i.gyazo.com/7f7b5aaac4f319ea32778d2ecf577e4e.gif)

**Comment by netgfx** [comment]
Nice I'll look into it.

**Comment by netgfx** [comment]
Now via the onHoverCallback, and onOutcallback you can apply custom logic to the hover events.
The main example shows the requested effect.

**Comment by McFarts** [comment]
Love it man, didn't think about the stroke. Great!!
