### ISSUE TITLE
fixedToCamera support?

### ISSUE THREAD

**Issue by tomatolicious** [netgfx/Phasetips#7]
Tried to hack this in myself and failed miserably. 

Any way to get the tooltips to appear fixed to camera? Right now in my scrolling world the tooltips scroll with the object they apply to.

**Comment by netgfx** [comment]
Is the item they apply to fixed to camera? If not I don't see how the tooltips could persist after it has scrolled.
One solution would be to apply the tooltips to something "stable". 
Or did I misunderstood?

**Comment by tomatolicious** [comment]
Yeah the item is fixed to camera! I want to use the tooltips on part of my ui in a game that has a free(mouse scrolling) camera. However, when placing the tooltip on an sprite that is fixed to camera, the tooltip appears way off and can only be found when scrolling the camera.

**Comment by netgfx** [comment]
I think the commit https://github.com/netgfx/Phasetips/commit/f4bb7f82a3092788ed876e192feb29f91e4a1a1d
fixes that.
Try it out and let me know.

**Comment by tomatolicious** [comment]
Can confirm that this fixes it! Works great now.

With that out of the way, buying you some tea on PayPal!

**Comment by netgfx** [comment]
That is great thanks!
